<!DOCTYPE html >
<?php
header('Content-type: text/html; charset=UTF-8');
?>
<html lang="en">
	<head>
    <title>Aide</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/grid_12.css">
    <script src="<?php echo $this->baseUrl();?>/js/jquery-1.7.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/jquery.easing.1.3.js"></script>
</head>
<body>
  <div class="main">
  <!--==============================header=================================-->
    <header>
        <h1><a href="index"><img src="<?php echo $this->baseUrl();?>/images/log.jpg" alt=""></a></h1> 
        <div class="clear"></div>    
        <nav class="box-shadow">
            <div>
                <ul class="menu">
                    <li><a href="apropos">A propos </a></li>
                     <li><a href="auth">Authentification</a>
                    <li><a href="campus">Campus</a></li>
                    <li><a href="contact">Contactez-nous</a></li>
                    <li><a href="aide">Aide</a></li>
                  
           
                </ul>
                 <div class="logoff">
                   <a href="index">EXIT</a>
                </div>
                <div class="clear"></div>
            </div>
        </nav>
    </header>   
  <!--==============================content================================-->
    <section id="content">
        <div class="container_12">
          <div class="grid_12">
            <div class="pad-0 border-1">
                <center><h1 class="top-1 p0">Aide</h1></center>
                <p class="p2">
<p>Bienvenue à College Campus , un service gratuit pour  acceder à vos informations. Afin de maintenir cet environnement et d'assurer une expérience utilisateur positive , nous devons limiter les abus qui menacent notre capacité à fournir ce service .</p>

<p>En conséquence , il ya quelques limites . Ces limites sont expliquées dans nos normes communautaires ci-dessous. S'il vous plaît respecter ces directives . </p>

<p><strong>La nudité et du matériel sexuellement explicite</strong></p>

<p>Si votre site contient du matériel sexuellement explicite , vous devez marquer le site comme ayant un contenu mature. Le contenu sera mis derrière un interstitiel , afin que les utilisateurs auront le choix de regarder ou pas regarder ce contenu . Si vous ne marquez pas votre site comme ayant un contenu mature et nous nous rendons compte que votre site contient des images ou vidéos avec la nudité ou de matériel sexuellement explicite , nous allons mettre le contenu derrière un interstitiel .</p>

<p>Il ya certains types de matériel sexuellement explicite que nous ne tolérons pas  . Nous ne permettons pas de la pornographie commerciale et les sites qui existent pour générer du trafic vers un site de pornographie commerciale . Les utilisateurs peuvent également ne pas publier des contenus incitant à la pédophilie , l'inceste ou bestialité .</p>

<p><strong>violence</strong></p>

<p>Les utilisateurs ne peuvent pas publier des menaces directes de la violence contre une personne ou un groupe de personnes . Nous demandons également aux utilisateurs de ne pas publier de contenu qui contient de la violence graphique .</p>

<p><strong>Discours haineux contre des groupes protégés</strong></p>

<p>Les utilisateurs ne peuvent pas publier des documents qui favorise la haine envers des groupes de personnes en fonction de leur race ou l'origine ethnique, la religion , le handicap , le sexe , l'âge , le statut de vétéran ou l'identité de l'orientation sexuelle / genre .</p>

<p><strong>imitation</strong></p>

<p>Nous ne permettons pas l'usurpation d'identité grâce à nos services d'une manière qui est destiné à ou ne trompeuses ou peu compréhensibles autres.</p>

<p><strong>Informations privées et confidentielles</strong></p>

<p>Nous ne permettons pas la publication non autorisée d'informations privées et confidentielles des personnes , telles que les numéros de cartes de crédit , numéros de sécurité sociale , conducteur et les autres numéros de licence et d'autres informations personnelles qui n'est pas accessible au public .</p>


Si vous croyez que quelqu'un viole ces normes communautaires , s'il vous plaît veuilez nous contacter ! </p>
            </div>
            </div>
            </div>
    </section> 
    
<!--==============================footer=================================-->
    <footer>
        <p>@ 2014 Campus</p>
    </footer>	    
</body>
</html>