<!DOCTYPE html>
<html lang="en">
<head>
    <title>Campus</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/grid_12.css">
    <script src="<?php echo $this->baseUrl();?>/js/jquery-1.7.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/jquery.easing.1.3.js"></script>
</head>
<body>
  <div class="main">
  <!--==============================header=================================-->
    <header>
        <h1><a href="index.php"><img src="<?php echo $this->baseUrl();?>/images/log.jpg" alt=""></a></h1> 
        <div class="clear"></div>    
        <nav class="box-shadow">
            <div>
                <ul class="menu">
                    <li class="home-page current"><a href="index.php"><span></span></a></li>
                    <li><a href="index/apropos">A propos </a></li>
                     <li><a href="index/auth">Authentification</a>
                    <li><a href="index/campus">Campus</a></li>
                    <li><a href="index/contact">Contactez-nous</a></li>
                    <li><a href="index/aide">Aide</a></li>
                  
           
                </ul>
                 <div class="logoff">
                   <a href="index">EXIT</a>
                </div>
                <div class="clear"></div>
            </div>
        </nav>
    </header>   
  <!--==============================content================================-->
    <section id="content">
        <div class="container_12">
          <div class="grid_12">
            <div class="pad-0 border-1">
                <center><h1 class="top-1 p0">Autres Campus</h1></center>
                
                <p class="p2"></p>
            </div>
            </div>
            </div>
    </section> 
    
<!--==============================footer=================================-->
    <footer>
        <p>© 2014 Campus</p>
    </footer>	    
</body>
</html>