<!DOCTYPE html>
<html lang="en">
<head>
    <title>Admin</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/grid_12.css">
    <script src="js/jquery-1.7.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    
	
</head>
<body>
  <div class="main">
  <!--==============================header=================================-->
    <header> 
    <h1><a href="index.php"><img src="<?php echo $this->baseUrl();?>/images/log.jpg" alt=""></a></h1>     
        <div class="clear"></div>    
        <nav class="box-shadow">
            <div>
                <ul class="menu">
                    <li class="home-page"><a href="index.php"><span></span></a></li>
                    <li><a href="index/apropos">A propos </a></li>
                     <li><a href="index/auth">Authentification</a>
                    <li><a href="index/campus">Campus</a></li>
                    <li><a href="index/contact">Contactez-nous</a></li>
                    <li><a href="index/aide">Aide</a></li>
                </ul>
                 <div class="logoff">
                   <a href="index">EXIT</a>
                </div>
                <div class="clear"></div>
            </div>
        </nav>
    </header>   
  <!--==============================content================================-->
    <section id="content">
        <div class="container_12">	
          <div class="grid_12">
            <div class="wrap pad-3">
                <div class="block-5">
                    <h3>Que voulez-vous faire?</h3>
                     <ul class="list-1">
                    	<li><a href="insetudiant">Ajouter un etudiant</a></li>
                        <li><a href="insprof">Ajouter un professeur</a></li>
                    </ul>
                </div>
                <div class="block-6">
                    <h3 class="p6">Soyez le bienvenue !</h3>
                    <div class="wrap">
                    	 <img src="<?php echo $this->baseUrl();?>/images/admin.jpg" alt class="img-border img-indent-2">
                        <div class="extra-wrap">
                            <p><a href="#" class="link"><strong>Ceci est votre espace administrateur</strong></a></p>
                            <p class="p6">Vous pouvez ici ajouter un professeur ou un etudiant.</p>
                    	</div>
                    </div>
                </div>
            </div>
          </div>
          <div class="clear"></div>
        </div> 
    </section> 
  <!--==============================footer=================================-->
    <footer>
        <p>© 2014 Campus</p>
    </footer> 
  
	    
</body>
</html>