<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ajout Professeur</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/grid_12.css">
    <script src="<?php echo $this->baseUrl();?>/js/jquery-1.7.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/js/jquery.easing.1.3.js"></script>
</head>
<body>
  <div class="main">
  <!--==============================header=================================-->
    <header>
        <div class="clear"></div>    
        <nav class="box-shadow">
            <div>
                <ul class="menu">
                    <li class="home-page current"><a href="index.php"><span></span></a></li>
                    <li><a href="index/apropos">A propos </a></li>
                     <li><a href="index/auth">Authentification</a>
                    <li><a href="index/campus">Campus</a></li>
                    <li><a href="index/contact">Contactez-nous</a></li>
                    <li><a href="index/aide">Aide</a></li>
                  
           
                </ul>
                 <div class="logoff">
                   <a href="index">EXIT</a>
                </div>
                <div class="clear"></div>
            </div>
        </nav>
    </header>   
  <!--==============================content================================-->
    <section id="content">
        <center><div class="container_12">
          <div class="grid_12">
            <div class="wrap pad-3">
                <div class="block-6"  Style="background:#55b7c8">
                    <center><h3>Ajouter Professeur</h3></center>
            <center>   <?php echo $this->form;?></center>
                </div>
            </div>
          </div>
          <div class="clear"></div>
        </div>
        </center>
    </section> 
  <!--==============================footer=================================-->
    <footer>
        <p>© 2014 Campus</p>
    </footer> 
  
</body>
</html>